### ISSUE TITLE
Handling of tokens

### ISSUE THREAD

**Issue by rarkins** [singapore/gl-got#37]
I think the last major version update changed how tokens are handled.

Previously, we were supporting only Personal Access Tokens with this code: https://github.com/singapore/gl-got/blob/15367eb11750b4e277ecd52e1863c808ebb352d4/index.js#L22-L24

Since v9.0.0, opts.token is passed through to `got` and I'm not sure if it's actually used there or not, based on the lack of hits for "token" here: https://github.com/sindresorhus/got/search?utf8=%E2%9C%93&q=token&type=

I was researching this code in the context of adding OAuth token support to this library in addition to Personal Access Token support, when I realised this unanticipated change in v9.

Cc @itaisteinherz @hbetts

**Comment by hbetts** [comment]
The token is set here - https://github.com/singapore/gl-got/blob/8fbdc0d44498172a2e1a14662f36f3ea286c46a1/index.js#L16

However, don't believe the new code works for Personal Access Tokens. 

It looks like [GitLab uses a different header for each type of token](https://docs.gitlab.com/ee/api/#oauth2-tokens).

(I don't actually use `gl-got` version 9 since I still have to support Node 6 users)

**Comment by hbetts** [comment]
Because the personal access token is advertised as the supported authentication method in this package's `README`, I consider the lack of proper personal access token support to be a serious regression. 

Therefore, I released `gl-got` 9.0.2 such that it once again supports the `PRIVATE-TOKEN` header when sending the token to GitLab.
